### ISSUE TITLE
Parameter fps for start_video_recording has no effect

### ISSUE THREAD

**Issue by FeralFox** [Andrey1994/screen_recorder_sdk#10]
I have recorded a video with start_video_recording and handed in different values for fps.
However, this did not have any effect, the frame rate of the video was always variable, around 20, although the parameter had a value of e.g. 3 fps.

**Comment by Andrey1994** [comment]
Hi, yes fps is variable and its a cool feature, not a bug. Your PC draws smth at variable framerate and recorded video should match this behavior.

Otherwise for example if you set fps to 30 but your PC rendered at 35(average) timing in video will not match real time

**Comment by Andrey1994** [comment]
in video header there is FPS value which you specify also each frame in video has its own time start and time stop, and this time is calculated based on real time between captured frames and doesnt depend on FPS(its correct because of comment above).

I am not sure but I think its up to video player to choose between FPS value in header and real timing per frame and most of them play video based on real time per frame
